language: php
php:
  - '5.6'

services:
  - docker

# Env Setup
before_install:
  - docker-compose run app ./deploy-dev.sh

script:
  - echo "Deploy Running..."

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy-dev.sh
    on:
      branch: dev

after_success:
  - echo "Deployed Successfully! \o/"
